name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Kubeconfig
        run: |
          aws eks update-kubeconfig --name petclinic-cluster --region ${{ secrets.AWS_REGION }}

      - name: Replace image tag
        run: |
          sed -i "s/__IMAGE_TAG__/${{ github.sha }}/g" k8s/deployment.yml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/